// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9m8T0oO4iPvG_zU02QarC8Wqek0H8N14',
    appId: '1:630973639309:web:967af659d31635e2fa50c4',
    messagingSenderId: '630973639309',
    projectId: 'e-commerce-app-5cda8',
    authDomain: 'e-commerce-app-5cda8.firebaseapp.com',
    storageBucket: 'e-commerce-app-5cda8.firebasestorage.app',
    measurementId: 'G-DGHNCV3T0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpiUG1K0UQILp0TG1g-7iRU1jRBKj-9zY',
    appId: '1:630973639309:android:c68ee51e663b88dcfa50c4',
    messagingSenderId: '630973639309',
    projectId: 'e-commerce-app-5cda8',
    storageBucket: 'e-commerce-app-5cda8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73Z45UsVB8zORxT6txEwEsnhu4fNQrlQ',
    appId: '1:630973639309:ios:80224031cf3206ecfa50c4',
    messagingSenderId: '630973639309',
    projectId: 'e-commerce-app-5cda8',
    storageBucket: 'e-commerce-app-5cda8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73Z45UsVB8zORxT6txEwEsnhu4fNQrlQ',
    appId: '1:630973639309:ios:80224031cf3206ecfa50c4',
    messagingSenderId: '630973639309',
    projectId: 'e-commerce-app-5cda8',
    storageBucket: 'e-commerce-app-5cda8.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9m8T0oO4iPvG_zU02QarC8Wqek0H8N14',
    appId: '1:630973639309:web:3a909df44698ba26fa50c4',
    messagingSenderId: '630973639309',
    projectId: 'e-commerce-app-5cda8',
    authDomain: 'e-commerce-app-5cda8.firebaseapp.com',
    storageBucket: 'e-commerce-app-5cda8.firebasestorage.app',
    measurementId: 'G-FRTRQ3N39B',
  );
}
